### ISSUE TITLE
Running one of the examples fails

### ISSUE THREAD

**Issue by 030** [arminc/clair-scanner#12] opened 2017-09-19 09:04 UTC
```
user@host /tmp $ ./clair-scanner_linux_amd64 nginx:1.11.6-alpine example-nginx.yaml http://127.0.0.1:6060 127.0.0.1
2017-09-19 11:03:45.952450 I | Analyzing 23f9039742dcfc7436c234a037aa1890b36b0a259e009687fe427aeb1691cd22
2017-09-19 11:03:45.954962 I | Analyzing faild: Could not analyze layer: Post http://127.0.0.1:6060/v1/layers: read tcp 127.0.0.1:58900->127.0.0.1:6060: read: connection reset by peer
```

**Comment by arminc** [comment] 2017-09-20 06:18
Duplicate of #13

**Closed** 2017-09-20 06:18 UTC
